# Generated by Django 4.1.7 on 2023-06-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calma_account', '0001_initial'),
        ('calma_account', '0002_createsuperuser'),
    ]

    operations = [
    ]
